---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# RawdataQC

<!-- badges: start -->
<!-- badges: end -->

整理转录组测序原始和比对数据的质量控制参数结果，并实现可视化展示。

## Installation

安装R包：

``` r
# install.packages("devtools")
devtools::install_github("lizhihui1996/RawdataQC")
```
## Example

加载R包：

```{r example}
library(RawdataQC)
## basic example code
```


```{r cars}
summary(QC)
```

结果示例:

```{r pressure, echo = FALSE}
p <- RawdataQC_standard(data=QC,xlab="library",ylab="gc_content",
                        changelabname=T,xlabname="Sample",ylabname="GC",
                        title=T,titlename="GC Content",
                        showerrordetail=F,
                        facet=T,facet_label="batch",
                        showerror=T,
                        limit=44.5)
p1 <- p$plot;p1
p2 <-p$summary;p2

p <- RawdataQC_stack(data=QC,xlab="library",showsample=T)
p3 <- p$failplot;p3
p4 <- p$faillist;p4
```

